### ISSUE TITLE
Question iBeacon dont get it going

### ISSUE THREAD

**Issue by Jason2866** [gemu2015/Sonoff-Tasmota#12]
Hello Gerhard,

enabled driver with `#define USE_IBEACON` and used this module http://www.ebyte.com/en/product-view-news.aspx?id=248
[E72-2G4M02S2B_Usermanual_v1.1.pdf](https://github.com/gemu2015/Sonoff-Tasmota/files/3784105/E72-2G4M02S2B_Usermanual_v1.1.pdf)
![IMG_0079](https://user-images.githubusercontent.com/24528715/67779061-6afab680-fa64-11e9-903f-725634755719.jpg)

Wired like on Page 6 Circuit design "USB" means 3.3V GND TX RX and connected and configured
![image](https://user-images.githubusercontent.com/24528715/67778365-5d90fc80-fa63-11e9-8ac0-9598b599a33a.png)

I get nothing in webconsole (even with log level 4)

**Comment by gemu2015** [comment]
https://github.com/arendst/Tasmota/wiki/iBeacon-driver

only these modules are supported


Von meinem iPhone gesendet
