### ISSUE TITLE
Communicate with SIM800L

### ISSUE THREAD

**Issue by pkkrusty** [gemu2015/Sonoff-Tasmota#52]
### PROBLEM DESCRIPTION
Trying to use scripting to communicate with SIM800L module to send and receive serial data via simple AT commands.

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x ] Device used (e.g., Sonoff Basic): Mini D1_____
- [x ] Tasmota binary firmware version number used: 13.0.0.1_____
  - [ ] Pre-compiled
  - [x ] Self-compiled
    - [x ] IDE / Compiler used: _VSC____
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```
  STATUS 0 output here:


```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ `weblog 4` _for more debug information)_
```
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
Trying to get a response back from the SIM800L module. Module Rx is hooked to GPIO1 (Tx) and Tx to Rx. My script is as follows:
```
>D 170
SB=4096
IP=192.168.4.1
command=""
res=0
rstr=""
substr=""
lat=0
lon=0
spd=0
>B
res=so(1 3 9600 8N1 170)
>T
lat=GPS#lat
lon=GPS#lon
>F
res=sa()
if (res>100) {
rstr=sr()
}
>S
print %substr% %rstr%
if (upsecs%10==0) {
print %5lat% %5lon% %res%
command=""
command="AT+CCID"
;=>serialsend2 %command%
sw(%command%)
}
```
Module is powered on and registered on cell network. What am I doing wrong with serial commands?

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by gemu2015** [comment]
you can not mix scripting serial cmd with tasmota serial send.

the cmd sw() is a script cmd and does not recognize %% but a string

sw(command)
